### ISSUE TITLE
[Feature Request] Warning for punishment messages

### ISSUE THREAD

**Issue by Toodixx** [BlueDevelopersInc/DiscordSRVUtils#100]
Would it be possible to get a warning message option for the punishment messages, including the warning they are on (e.g first warning, second etc) and who warned them?

I am currently using AdvancedBans which allows auto punishment to be issued after so many warnings so I feel the feature would be helpful for staff

**Comment by BlueTree242** [comment]
this feature was added and it is available in dev builds (its included in the punishments rework) download dev builds [here](https://ci.bluetree242.tk/job/DiscordSRVUtils/)
