### ISSUE TITLE
[Feature Request] Expand on punishment logging

### ISSUE THREAD

**Issue by kayalambrechts** [BlueDevelopersInc/DiscordSRVUtils#101]
**Is your feature request related to a problem? Please describe.**

- Currently, the punishment logger is quite limited, certain messages can't be disabled, and there's no possibility for multiple channels to be used.

**Describe the solution you'd like**

- Add the possibility to disable a message by setting it blank (ex. below)

- Add an array to each message specifying which channels, or allow an array in 'punishment_messages_channel:'
`#Message to send when a person is Temporary IP banned. (set to '' to disable)
temp_ip_banned_message: 'message:ban'
#Channels this message will get sent in, 0 for default DiscordSRV channel - Doesn't work if above is blank
- '0'
- '0'`

**Describe alternatives you've considered**

- none

**Additional context**

**Comment by BlueTree242** [comment]
A part of this feature request is done, you can find it [here](https://ci.bluetree242.tk/job/DiscordSRVUtils). this adds support for multiple channels **but not for every message**, this will be added soon.

**Comment by BlueTree242** [comment]
this feature request should be fully added now, it will be merged into develop soon, and sooner to major builds!
