### ISSUE TITLE
[Feature Request] Disable certain commands

### ISSUE THREAD

**Issue by kayalambrechts** [BlueDevelopersInc/DiscordSRVUtils#106]
**Is your feature request related to a problem? Please describe.**
When most features in the plugin aren't used, the commands are still registered.
This leads to a lot of unnecessary commands, viewable for anyone.

**Describe the solution you'd like**
An option to disable every command seperately.

**Describe alternatives you've considered**
none

**Additional context**

**Comment by kayalambrechts** [comment]
Just checked config, seems to already be a thing!

**Comment by Creeperz653** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] When most features in the plugin aren't used, the commands are still registered. This leads to a lot of unnecessary commands, viewable for anyone.
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen. An option to disable every command seperately.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered. none
> 
> **Additional context** Add any other context or screenshots about the feature request here.

A clear and concise description of what the problem is. Ex. I'm always frustrated when [people who dont check config]
When most features in the plugin aren't used, the commands are still registered.
This leads to a lot of unnecessary commands, viewable for anyone.

**Comment by BlueTree242** [comment]
This was already added a month ago in dev builds
