### ISSUE TITLE
[Feature Request] custom status channel emoji

### ISSUE THREAD

**Issue by Creeperz653** [BlueDevelopersInc/DiscordSRVUtils#108]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
I would like it so when the server is online it would change the channel name to a green emoji and when its offline it would change to red emoji ofc you would need (emoji)| (name) in config but it would work also custom emojis would cool would be done by a config asking for channel name when offline channel name when online channel name when some of servers are offline online (if you allow more then one server to be in #status)
**Describe alternatives you've considered**
No
**Additional context**
![image](https://user-images.githubusercontent.com/76449952/171313817-df53f3b3-9be4-45f1-94ab-cbd3780c01dc.png)

**Comment by BlueTree242** [comment]
The problem would be that the status isn't accurate, if server is killed, the channel name won't get updated, just anything that caused unexpected stop.. It still say "online"

**Comment by Creeperz653** [comment]
> The problem would be that the status isn't accurate, if server is killed, the channel name won't get updated, just anything that caused unexpected stop.. It still say "online"

I see. Maybe proxy can updated all of it at same time

**Comment by BlueTree242** [comment]
Plugin only supports bukkit currently

**Comment by Creeperz653** [comment]
> Plugin only supports bukkit currently

no? a proxy can send packets to bukkit or using database

**Comment by BlueTree242** [comment]
There is no proxy version to send + server would be off
