### ISSUE TITLE
[Feature Request] Vote Logging 

### ISSUE THREAD

**Issue by LazyyPumpkinn** [BlueDevelopersInc/DiscordSRVUtils#113]
NuVotifier/votifer vote logging to a discord channel. (Nuvotifier is also for bungee/velocity proxy server so you may keep that in mind to support it if this is possible) 
 I don't think i need to explain anything else than this :|

**Comment by BlueTree242** [comment]
This is possible with discordsrv alerts system tho

**Comment by BlueTree242** [comment]
For bungee/velocity support nuvotifier can forward the vote to backend servers, and anyway DiscordSRVUtils doesn't support them. You can send a message to discord when someone votes using alerts system

**Comment by LazyyPumpkinn** [comment]
Since when discordsrv got alert system

**Comment by BlueTree242** [comment]
Uhh since years....

**Comment by LazyyPumpkinn** [comment]
I am such a dumb, i never check alerts.yml
