### ISSUE TITLE
[Feature Request]   Suggestion threads feature

### ISSUE THREAD

**Issue by Creeperz653** [BlueDevelopersInc/DiscordSRVUtils#114]
**Is your feature request related to a problem? Please describe.**
Unable to discuss the suggestion 

**Describe the solution you'd like**
Using discord thread feature

**Comment by BlueTree242** [comment]
DiscordSRV uses jda 4 which means the bot cannot see, create threads for the bot threads feature does not exist, when discordsrv 2.0 is released it will be added
