### ISSUE TITLE
[Feature Request] Improve leveling system

### ISSUE THREAD

**Issue by LazyyPumpkinn** [BlueDevelopersInc/DiscordSRVUtils#115]
Players of my server got to 100+ level in just few days(barely 2-4) 
You get level up too fast bruh, in bots like mee6 if you are like 50 level, it takes days or even weeks just to get to 51 level😐
Or maybe able to customize so that if you are level 1 you need 100 messages to level up to 2 level. And if you are 5 level, you need 150 messages to level up to 6 level(customizable).

**Comment by BlueTree242** [comment]
Current leveling system:

Every time a player sends a message plugin generates a random number between 1 and 50.. And adds it to xp, if the xp reaches 300+ they levelup and xp is reset and the same process repeats (note if antispam is enabled in your config a player only gets their xp gain one time in a minute)  

And this is why everyone levels up easily if they already chat alot, i will check how mee6 works and let you know if any progress

**Comment by LazyyPumpkinn** [comment]
> Current leveling system:
> 
> Every time a player sends a message plugin generates a random number between 1 and 50.. And adds it to xp, if the xp reaches 300+ they levelup and xp is reset and the same process repeats (note if antispam is enabled in your config a player only gets their xp gain one time in a minute)
> 
> And this is why everyone levels up easily if they already chat alot, i will check how mee6 works and let you know if any progress

Just make the random xp per message configurable, also the amount of xp needed to level up zper *level

**Comment by BlueTree242** [comment]
https://github.com/Mee6/Mee6-documentation/blob/master/docs/levels_xp.md

This is what mee6 does

**Comment by LazyyPumpkinn** [comment]
> https://github.com/Mee6/Mee6-documentation/blob/master/docs/levels_xp.md
> 
> This is what mee6 does

Yeah the exp to level up increase every level

**Comment by BlueTree242** [comment]
Implemented, you can download new dev builds from [here](https://ci.bluetree242.ml/job/DiscordSRVUtils)
