### ISSUE TITLE
[BUG] Error

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [BlueDevelopersInc/DiscordSRVUtils#117]
**Describe the bug**
Error on console while using placeholders

**To Reproduce**
Use a placeholder in another plugin

**Expected behavior**
No error should occur

**Screenshots**
https://pastebin.com/rPy9naZv

**Server Information:**
 - Version: 1.19
 - Software: Paper

**Plugin Information:**
 - Version: 1.2.9
 - DiscordSRV Version 1.25.1
 - Build Number None

**Additional context**
N/A

**Comment by PhoenixCodingStuff** [comment]
Yea `/rank` command on discord works , just giving the error while using it on the scoreboard

**Comment by BlueTree242** [comment]
are you sure? screenshot `/rank` command

**Comment by BlueTree242** [comment]
It's been a while and i haven't heard from you, whe what you are saying makes no sense... Can you please dm me on discord?

**Comment by Creeperz653** [comment]
Ya

**Comment by BlueTree242** [comment]
Error fixed in [dev builds](https://ci.bluetree242.tk/job/DiscordSRVUtils)
