### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by noulalu** [BlueDevelopersInc/DiscordSRVUtils#118]
**Describe the bug**
The folder is not being created and there is no response to the /dsu command
**To Reproduce**
1. Use '...' command
2. Send a random message
3. React with '...'
install discordsrvutils, and install discordsrv. run the server once.
**Expected behavior**
a folder to be created, and the commands to work
**Screenshots**

**Server Information:**
 - Version: [e.g. 1.18]
 - Software: [e.g. Paper]
1.8 spigot
**Plugin Information:**
 - Version: [e.g. 1.2.7]
 - DiscordSRV Version [e.g. 1.24.0]
 - Build Number (run `/dsu` to find out, if it doesn't tell you then none)
latest
**Additional context**

**Comment by BlueTree242** [comment]
Bro, you didn't remove any of the examples, edit your message and remove the examples please

**Comment by BlueTree242** [comment]
Closed because no details were sent
