### ISSUE TITLE
[Feature Request] Server status as channel name

### ISSUE THREAD

**Issue by TomSipsOnCurry** [BlueDevelopersInc/DiscordSRVUtils#119]
So previously I made a discord bot that shows the status of the server as a channel name. But since I couldn't access data from the server rather had to use an api, it would try to constantly update every 20 minutes and go past the discord cooldown. So it would be cool if you could add a feature that allows this feature and only updates when the server turns off or when players join/leave.

So by doing /status you can choose if you want it as a message or channel name. Then it lets you choose the channel if you chose channel name. If the server is turned off, the channel will read "🔴Offline" on the other hand, if its online it would say something like "🟢Online: 3/15". The message would only update if a player joins/leaves or if the server is turned off/on. So that the discord limit for channel name edits wont be reached.
![image](https://user-images.githubusercontent.com/78724847/190110188-e07002c0-bea1-420f-91ab-a370e78b17d2.png)

**Comment by BlueTree242** [comment]
closing this because as mentioned in discord the rate limit will limit this badly
