### ISSUE TITLE
[Feature Request] Ability to reset levels.

### ISSUE THREAD

**Issue by Shamwarizim** [BlueDevelopersInc/DiscordSRVUtils#120]
**Is your feature request related to a problem? Please describe.**
Currently there is no way in order to reset levels entirely or of specific players.

**Describe the solution you'd like**
Have a way to use bot commands in order to reset levels entirely, or for a specific player.

**Describe alternatives you've considered**
An alternative could be editing something in the files such as in the config.yml file to reset levels.

**Comment by BlueTree242** [comment]
Feature available since build [#174](https://ci.bluetree242.ml/job/DiscordSRVUtils/174/) `/dsu resetlevel`
