### ISSUE TITLE
[Feature Request] STAFF CHAT

### ISSUE THREAD

**Issue by Miner16** [BlueDevelopersInc/DiscordSRVUtils#125]
SUGGESTION: Add a staff chat for the plugin. So you can write in a channel and the staff members will also receive the message ingame. Like the plugin: [staff chat](https://www.spigotmc.org/resources/discordsrv-staff-chat.44245/)

**Comment by BlueTree242** [comment]
I don't get it, why add something another plugin does already

**Comment by Miner16** [comment]
I know, there is a plugin for everything, but it would be cool if I didn't have to install multiple plugins. and it is a cool feature

**Comment by BlueTree242** [comment]
I am still confused, what's wrong with adding a new jar to your plugins folder, there is no extra resource usage, you don't need any more ram or cpu, these discord stuff are small, not heavy

**Comment by BlueTree242** [comment]
Do you use a host that limit the amount of plugins or something

**Comment by BlueTree242** [comment]
Closing this as i see no point of adding it, and author did not provide any reasons
