### ISSUE TITLE
[BUG] Error when trying to create a ticket panel

### ISSUE THREAD

**Issue by CaptainRexPL** [BlueDevelopersInc/DiscordSRVUtils#134]
**Describe the bug**
When the bot asks me to mention a channel where it should send the panel and I do it I get an error: ❌ You did not mention a channel. Please try again

**To Reproduce**
1. Use /createpanel command
2. Proceed to step 2
3. Mention a channel

**Expected behavior**

**Screenshots**

**Server Information:**
 - Version: [e.g. 1.18]
 - Software: [e.g. Paper]

**Plugin Information:**
 - Version: 1.19.3 paper
 - DiscordSRV Version [e.g. 1.26.1]
 -  Build None/Unknown

**Additional context**

**Comment by BlueTree242** [comment]
This is not a bug, you did not enable `Message Content Intent` in the developer portal, which discordsrv should've told you to do so already

**Comment by PSYCHEER** [comment]
![image](https://github.com/BlueDevelopersInc/DiscordSRVUtils/assets/42911029/b8592697-ac10-4b68-b099-3e253fc4930c)
![image](https://github.com/BlueDevelopersInc/DiscordSRVUtils/assets/42911029/8af95b88-c5f9-4248-9efb-9945e2366fd7)
I restarted server, all of servers, proxy a few times...always see this..
