### ISSUE TITLE
Banned role

### ISSUE THREAD

**Issue by dmitr-ukhin** [BlueDevelopersInc/DiscordSRVUtils#15]
Great addon! Thank you!

I think it would be very useful to add an option not to ban banned or tempbanned person form Discord server.
Instead you can simply give him a muted or banned role. I'll be very happy to use this feature.

**Comment by BlueTree242** [comment]
> Great addon! Thank you!
> 
> I think it would be very useful to add an option not to ban banned or tempbanned person form Discord server.
> Instead you can simply give him a muted or banned role. I'll be very happy to use this feature.

Very good suggestion! I will add it

**Comment by dmitr-ukhin** [comment]
thank you!

**Comment by dmitr-ukhin** [comment]
Hello again! I am sorry for re-oppening, but I see status "Fixed" and anyway I can't find this feature in plugin. It is already available or just planned to be added?

**Comment by BlueTree242** [comment]
I think it was closed by accident

**Comment by BlueTree242** [comment]
I am adding it in the exact next version

**Comment by BlueTree242** [comment]
Added in 1.1.13

**Comment by UniDima** [comment]
Can you add this feature back in v1.2+please?

**Comment by BlueTree242** [comment]
Added in [dev builds](https://ci.bluetree242.tk/job/DiscordSRVUtils/)

**Comment by BlueTree242** [comment]
The feature is now in offical builds (1.2.6)

**Comment by Creeperz653** [comment]
> Can you add this feature back in v1.2+ please?

LOL I asked him to add it to suggest and he did it fast

**Comment by BlueTree242** [comment]
> > Can you add this feature back in v1.2+ please?
> 
> LOL I asked him to add it to suggest and he did it fast

what? wdym

**Comment by UniDima** [comment]
Feature is working fine, thank you!

**Comment by Creeperz653** [comment]
im the reason he readded it

**Comment by Creeperz653** [comment]
i told him to add banned roles

**Comment by BlueTree242** [comment]
> im the reason he readded it

You aren't

**Comment by Creeperz653** [comment]
> > im the reason he readded it
> 
> You aren't

stop lying
