### ISSUE TITLE
Slash Commands Support

### ISSUE THREAD

**Issue by cmod31** [BlueDevelopersInc/DiscordSRVUtils#86]
Hey,
Could you add slash commands? its a bit annoying to search for the right commands/arguments and spam a few commands. You could also add autocomplete with this instead of multiple messages for the ticket panel creation and make these fancy invisible messages that only the user can see.
Would be nice and thanks for the discord bot!

**Comment by BlueTree242** [comment]
no problem, i will work on it, i will just have to rewrite the commands, which will take a while, also i never tried slash commands so i have no idea how it works, but anyways, i will add them!

**Comment by cmod31** [comment]
Thanks thats very nice but take your time my Minecraft Server network is also not finished now

**Comment by cmod31** [comment]
Also reaction roles would be a  cool feature there is this new menu thing in the discord api
<video src="https://minewar.net/discordbotsuggestion1.mp4" controls="" style="width:70%;"></video>

**Comment by BlueTree242** [comment]
not allowed multiple suggestions in 1 issue

**Comment by Creeperz653** [comment]
it would be nice if you used the discord mate https://discord.com/invite/Bmmkp8kB

**Comment by BlueTree242** [comment]
Github is better than discord in this 10000 times

**Comment by Creeperz653** [comment]
i dont talk to children

**Comment by BlueTree242** [comment]
About auto completion, DiscordSRV still uses jda 4 which doesn't support it, and if they update the addon will break (i will get ready for it anyways)... Idk if they will update or not but currently, not possible, until discordsrv updates jda, and for discordsrv to update they need to do a few changes to events and their listeners, prob some changes with the discordsrv events, so i think auto completion just isn't so important, also, i will later send you some advantages and disadvantages of switching to slash commands

**Comment by cmod31** [comment]
so slash commands are impossible at all for now? or what do you mean with auto completion.
Also you use full Java to make the bot and the bot that i showed in the mp4 uses javascript so is it unsupported with java or why is it unsupported?

**Comment by cmod31** [comment]
sorry i had to read more i read discord not discord srv so i think we have to wait is there an github issue for it?

**Comment by BlueTree242** [comment]
> sorry i had to read more i read discord not discord srv so i think we have to wait is there an github issue for it?

Its issue with discordsrv. With auto completing not slash commands themselfs

**Comment by BlueTree242** [comment]
> no you have to wait for blue to fix the errors

What errors huh, its outdated jda from discordsrv

**Comment by cmod31** [comment]
ok so new issue on the discordsr github repo or what?

**Comment by BlueTree242** [comment]
> ok so new issue on the discordsrv github repo or what?

Well yes but i don't think they care about the addon so they just won't update, also jda 5 would probably break some other addons (including this one but im preparing) so there is a high chance it won't happen soon

**Comment by BlueTree242** [comment]
Please confirm that you want slash commands to be how commands work on this plugin

**Advantages**
- Easier way to find the commands
- Less chance of errors on some  commands
- Plugin will be considered modern
- Ability to use those hidden messages
- Removal of prefix config option

**Disadvantages**
- Startup errors because of the missing slash commands scope for few people, some people will just think dead plugin and won't use it
- Slash Commands is a new discord feature, not everyone knows how to use it, at first i didn't even like them
- A little slower execution of commands


Let me know if i forgot something

**Comment by Creeperz653** [comment]
then put in startup That It needs the slash commands scope
and it won't be slower it depends on the ram
also, slash commands aren't that hard
also, add a option to use prefix and slash commands at same time

**Comment by cmod31** [comment]
The thing is all of the bots i'm using on discord servers are using slash commands. So its not a new feature at all. Warn the user somehow and most of the bots use both slash and prefix. mee6 has an option that you have to manually enable slash commands first and others just let !help in it.

**Comment by BlueTree242** [comment]
> then put in startup That It needs the slash commands scope and it won't be slower it depends on the ram also, slash commands aren't that hard also, add a option to use prefix and slash commands at same time

Its slower due to discord client, its slower to type, also it isnt easy to make it support both

**Comment by Pukimaa** [comment]
Isn't supporting both not that hard? I myself make Discord Bots since a few years and Slash Commands basically just emits an event like the message create event so the bot could listen to both the prefix (with the message creation event) and to the interaction creation event. Actually also porting theese over isn't that hard because you just need to transform the arguments to options. I'll look into the code more deeply but for now that's all I can say.

**Comment by BlueTree242** [comment]
> Isn't supporting both not that hard? I myself make Discord Bots since a few years and Slash Commands basically just emits an event like the message create event so the bot could listen to both the prefix (with the message creation event) and to the interaction creation event. Actually also porting theese over isn't that hard because you just need to transform the arguments to options. I'll look into the code more deeply but for now that's all I can say.

You don't get what i mean, what you are saying is not hard, this isn't what i meant, some jda users don't recommend doing it anyways, i will be thinking of it

**Comment by Creeperz653** [comment]
i asked bluetree for slash commands Lol he said he was working on it but he stopped  I think this was a few months ago

**Comment by cmod31** [comment]
So whats the current state now? Waiting for discordsrv jda update?

**Comment by BlueTree242** [comment]
No, im busy these days, it would be appreciated if you wait a few weeks i am really busy

**Comment by BlueTree242** [comment]
im sorry for being late, the feature is ready on its branch, since all commands were recoded i must test all of them so please wait for everything to be stable and it will be available to everyone

**Comment by BlueTree242** [comment]
Slash Commands Available starting from Build 77, [Download Here](https://ci.bluetree242.tk/job/DiscordSRVUtils)

**Comment by Creeperz653** [comment]
I suggested it before this guy proof![image](https://user-images.githubusercontent.com/76449952/177439504-9865285c-66c0-40ed-995b-ca315a4186a8.jpeg)

**Comment by BlueTree242** [comment]
Does it matter?
