### ISSUE TITLE
Suggestion: Time-out function instead of mute roles

### ISSUE THREAD

**Issue by larssieboy18** [BlueDevelopersInc/DiscordSRVUtils#88]
As suggested in the Discord channel: Use the new Discord timeout function instead of applying a "mute role" when a user gets muted in Minecraft.

(See https://discord.com/channels/741675514707705887/741684129514389576/928209274696507413 & https://discord.com/channels/741675514707705887/741684129514389576/928272444693819402)

**Comment by BlueTree242** [comment]
Will surely add that, but we will wait for discordsrv to update jda any time soon, i can't add it until they do that

**Comment by BlueTree242** [comment]
Closing until discordsrv 2.0 is released
