### ISSUE TITLE
Leaderboard Status & Echo

### ISSUE THREAD

**Issue by MpLLLL71** [BlueDevelopersInc/DiscordSRVUtils#89]
Hi !

- Make leaderboard in realtime like status with time refresh.
- Make a command sendmessage (like testmessage) for send personnal embed (no with e.replyMessage but e.sendMessage)

**Comment by BlueTree242** [comment]
I don't get what you mean in part 2

**Comment by BlueTree242** [comment]
Wdym "personal embed"

**Comment by BlueTree242** [comment]
I think i got what you mean, it better be named "echo"

**Comment by BlueTree242** [comment]
Your first suggestion is probably getting added, the second one is probably going to be added but in a better way, you use command `!echo` and bot will send a link, you build your embed and choose channel and click send, do you think this is a good idea?

**Comment by BlueTree242** [comment]
I think he means the leveling.....

**Comment by BlueTree242** [comment]
the echo command was added, however the leaderboard status was not added as it doesn't look like anyone cares about it
