### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by KorenYT123** [BlueDevelopersInc/DiscordSRVUtils#97]
![image](https://user-images.githubusercontent.com/89277466/155226980-bc21c937-1b47-4cb7-8f6d-eb8843cb3c98.png)
Possibility to change this message.

**Comment by BlueTree242** [comment]
Simply not possible, its not hard coded

**Comment by KorenYT123** [comment]
Is it possible to cancal(disable) this command?

**Comment by BlueTree242** [comment]
Yes, its on the first page on the wiki

**Comment by KorenYT123** [comment]
I know it is possible to block in a specific place but there is an option to cancel the command because it is still possible to register it in DM
