### ISSUE TITLE
[Feature Request] ticket log

### ISSUE THREAD

**Issue by vincentwang0905** [BlueDevelopersInc/DiscordSRVUtils#98]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
create ticket log
can be text or...
and send to the specified channel

**Describe alternatives you've considered**
can be text file

**Additional context**
NO

**Comment by BlueTree242** [comment]
Can you describe your request, 2 words wont explain anything, we need a long explanation on what you want and how you expect it to work

**Comment by BlueTree242** [comment]
It has been 12 days you didn't clearify what your feature request, i have to close it
