### ISSUE TITLE
[Feature Request] Leveling Rewards

### ISSUE THREAD

**Issue by Apiz05** [BlueDevelopersInc/DiscordSRVUtils#99]
### **Is your feature request related to a problem? Please describe.**
I really want this will be a feature cause it will make the server more active right now my server is not active and mostly like ded

### **Describe the solution you'd like**
Player can connect their acc from discord and ingame and if the player talk in the discord server 
they can get money too

but if the player doesn't link their acc the money will go to a nother database waiting for it to connect 
if the player link the acc it will automaticly transfer to the server side acc 

### **Describe alternatives you've considered**
maybe use an api or use a same database that connect with the vault

### **Additional context**
I hope you will add this

**Comment by BlueTree242** [comment]
Hello, i can't make the feature direct to "money" but i can make the plugin execute some commands when some conditions are met, for example `/eco give (player name) (money)`

**Comment by BlueTree242** [comment]
Added in [dev builds](https://ci.bluetree242.ml/job/DiscordSRVUtils)  documentation will be written soon
